### ISSUE TITLE
Api keys are deprecated in favor of personal tokens

### ISSUE THREAD

**Issue by vojkny** [fuxingloh/airtable#15]
> If you or a developer on your team has used an Airtable API key to build API integrations with Airtable, please migrate to using [personal access tokens](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=1040434f2dca4e69a29c8be6e83c0374&_e=aUPdmfdVm5UdAQ4dPy86VIj01GGgC8nMgaMc97DEkHhctG7rv5AzJq70P032KELRltZ4fbaqpWeqt7dyjBnnvXgXmZVc6h9ZViBDq-YOfAYKS-S8X3XPIU9UOFevOzPECBM868qF_kEQY8dFwHPFXpaTM4S4jWO3HzZ1i9t7LzEE67s-Wyy5eHINpr2KTAhrBbtL-U6FUmg3-fZ4X1lV-hSlOIv4NdGOAdQmnYW0zkrfLl1khK0gy4U4ldvVRrn_Y3YD5YrIv5WeN1ckCBbiutH6Gl_u7iYIT2crn3aEADWiWh0cfkekKLhTWumJXvsP-e-2ekTlhK2ATDrTtK2-DeSqNTVLCM_5wYChjCK-NlmsIUIaBN9Cu1kP5Iwlr1795nwHMyjK_rxbz-EsPTgKkv21wzkJ8yicB4HBfi5hbpOhuy0lX5NdOp6RO9D-b1jB) to authenticate your API requests before February 1st 2024. Your API key usage can be directly replaced with a personal access token provided as an Authorization: Bearer header.
>
> In summary, Personal Access Tokens and OAuth are now available (as of January 2023). Airtable API keys will be [deprecated](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=1040434f2dca4e69a29c8be6e83c0374&_e=aUPdmfdVm5UdAQ4dPy86VHiiwcZCDPtMplAgVQxepXuXHbGpM4KTnNtjdT2bYXlMLwOtl6efw18Y73rF_3yfcC7QWTh01_ok2q6sq0Ve5XtqEoCGvwsi3_Nvvnq-XJUQO18W6kp5Cljpnp33BZrrMUr4SqFNun2j3_XmN79Sf4YfQX_Xec0oCi1NKAMeaINny_x-POqQM5lpymjfldAIgjBWmKWCcORt0UQBNpaDILhhEB62jNGpwu8kGJOqU13KOiay6D1rGCYY1ewzUUf4BeKIEPZoNKBoAX-i3_CdA9r2U6rBJH5iwXHGfK09WSKg35Y4ISaYO8eeaswzxw210ajfn-lpFvOUIp8wO12_0FMHYnxQfjyk3HlbatGD6HGMdXmSOcK6vypVc0B8ex1d6fRauJCX7Ke0HWBVjywBrN24wM96_88BWX2b41G0Q3pG) on the following timeline:
> 
> August 1st, 2023: Users will no longer be able to create new API keys
> February 1st, 2024 (next year): Existing API keys cannot be used to access the Airtable API

I tried to replace the api key with the token, but then the code does not work. Could you please extend the authorization with access tokens? 🙏

**Comment by knyttl** [comment]
🙏

**Comment by knyttl** [comment]
pls pls

**Comment by vojkny** [comment]
🙏
