### ISSUE TITLE
Additional Functionality in AirtableApplication

### ISSUE THREAD

**Issue by RobertBoylanAOC** [fuxingloh/airtable#5]
Hi,

I've found your API very useful so far. I was wondering if maybe you could consider adding the following functionality to AirtableApplication API:

1. A method to get the name and/or the id of the base. At the moment it seems as though you can only retrieve the base name from the AirtableTable class.

2. List all of the tables in a given base.

3. Count how many records in total are in a given base.

Thanks,

Robert Boylan

**Comment by fuxingloh** [comment]
Hi,

This REST API is implemented accordingly to the specification provided in `https://airtable.com/api`. Because those features are not available or documented in the specification, I won't be able to implement them. 😕

**Comment by RobertBoylanAOC** [comment]
Hi Fuxing,

That makes perfect sense. Apologies, on second thought I should have looked at the official Airtable API docs first. 

Thanks for the reply!
